# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SaveItForLater' do
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'MBProgressHUD'
end

target 'SaveItForLaterTests' do

end

target 'SaveItForLaterUITests' do

end

